export const TOOLS = [
  {
    id: 'earnings-intel',
    name: 'Earnings Intel',
    tagline: 'Earnings calendar & insider tracking',
    description: 'Track earnings reports, analyst estimates, price reactions, and insider transactions across your portfolio and watchlist.',
    icon: 'BarChart3',
    color: 'blue',
    route: '/earnings-intel',
    status: 'live' as const,
  },
  {
    id: 'sector-momentum',
    name: 'Sector Momentum',
    tagline: 'Sector rotation & thematic momentum',
    description: 'Track sector rotation across GICS sectors and thematic baskets with relative strength, volatility, and RSI metrics.',
    icon: 'Activity',
    color: 'orange',
    route: '/sector-momentum',
    status: 'live' as const,
  },
  {
    id: 'snap-judgement',
    name: 'SnapJudgement',
    tagline: 'Five-minute investment briefs',
    description: 'Enter any ticker → get a structured investment brief with valuation, sentiment, financials, and price behavior.',
    icon: 'Zap',
    color: 'amber',
    route: '/snap-judgement',
    status: 'live' as const,
  },
  {
    id: 'market-narrative',
    name: 'Market Narrative',
    tagline: 'Understand why assets moved',
    description: 'Translates price action into structured, plausible narratives — explaining why assets moved with sector and regime context.',
    icon: 'FileText',
    color: 'rose',
    route: '/market-narrative',
    status: 'live' as const,
  },
  {
    id: 'dip-snipe',
    name: 'DipSnipe',
    tagline: 'Daily stock market losers',
    description: 'Identify and analyze daily stock market losers across sectors, industries, and market-cap ranges.',
    icon: 'TrendingDown',
    color: 'red',
    route: '/dip-snipe',
    status: 'live' as const,
  },
  {
    id: 'superinvestor-lab',
    name: 'SuperInvestor Lab',
    tagline: 'Analyze stocks through legendary investors',
    description: 'See how any stock stacks up against the philosophies of 25+ legendary investors — Graham, Buffett, Lynch, and more.',
    icon: 'GraduationCap',
    color: 'purple',
    route: '/superinvestor-lab',
    status: 'live' as const,
  },
  {
    id: 'ath-distance',
    name: 'ATH Distance',
    tagline: 'Distance from all-time-highs by sector',
    description: 'Measures how far stocks are from their all-time highs, broken down by sector and industry with filters.',
    icon: 'Mountain',
    color: 'emerald',
    route: '/ath-distance',
    status: 'live' as const,
  },
  {
    id: 'portfolio-merge',
    name: 'Portfolio Merger',
    tagline: 'Merge multiple portfolio files',
    description: 'Upload multiple portfolio files (CSV/XLSX), combine by ticker with live P&L, donut charts, and PDF reports.',
    icon: 'FolderOpen',
    color: 'teal',
    route: '/portfolio-merge',
    status: 'live' as const,
  },
]


